USE TcAppleTest;
--заполнение таблицы Nodes
INSERT INTO Nodes (Phone, Name) VALUES (901, 'C# developer');
INSERT INTO Nodes (Phone, Name) VALUES (130, 'HR');
INSERT INTO Nodes (Phone, Name) VALUES (902, 'Linux admin');
INSERT INTO Nodes (Phone, Name) VALUES (400, 'Бухгалтерия');
INSERT INTO Nodes (Phone, Name) VALUES (502, 'Ведущий специалист');
INSERT INTO Nodes (Phone, Name) VALUES (444, 'Главный бухгалтер');
INSERT INTO Nodes (Phone, Name) VALUES (501, 'Главный специалист');
INSERT INTO Nodes (Phone, Name) VALUES (910, 'Группа 1С');
INSERT INTO Nodes (Phone, Name) VALUES (100, 'Директор');
INSERT INTO Nodes (Phone, Name) VALUES (301, 'Завхоз');
INSERT INTO Nodes (Phone, Name) VALUES (300, 'Заместитель по АХЧ');
INSERT INTO Nodes (Phone, Name) VALUES (401, 'Зарплатова Наталья');
INSERT INTO Nodes (Phone, Name) VALUES (131, 'ИТ-рекрутер');
INSERT INTO Nodes (Phone, Name) VALUES (317, 'Мастер');
INSERT INTO Nodes (Phone, Name) VALUES (135, 'Менеджер по персоналу');
INSERT INTO Nodes (Phone, Name) VALUES (999, 'Начальник');
INSERT INTO Nodes (Phone, Name) VALUES (600, 'Отдел безопасности');
INSERT INTO Nodes (Phone, Name) VALUES (900, 'Отдел ИТ');
INSERT INTO Nodes (Phone, Name) VALUES (918, 'Отчётова Мария');
INSERT INTO Nodes (Phone, Name) VALUES (305, 'Плотников Сергей');
INSERT INTO Nodes (Phone, Name) VALUES (911, 'Программист 1 категории');
INSERT INTO Nodes (Phone, Name) VALUES (310, 'Сантехники');
INSERT INTO Nodes (Phone, Name) VALUES (912, 'Семёнов Алексей');
INSERT INTO Nodes (Phone, Name) VALUES (315, 'Слесарев Антон');
INSERT INTO Nodes (Phone, Name) VALUES (309, 'Уборщица');
--заполнение таблицы NodeRefs 
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (100, 112);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (100, 120);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (100, 130);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (100, 300);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (100, 400);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (100, 500);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (100, 900);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (130, 131);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (130, 135);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (300, 301);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (300, 305);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (300, 309);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (300, 310);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (310, 315);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (310, 317);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (400, 401);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (400, 444);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (600, 501);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (600, 502);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (900, 121);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (900, 901);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (900, 902);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (900, 910);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (900, 999);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (910, 911);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (910, 912);
INSERT INTO NodeRefs (ParentPhone, Phone) VALUES (910, 918);